MAZE_SIZE = WIDTH, HEIGHT = 902, 802
CELL_SIZE = 50
cols, rows = WIDTH // CELL_SIZE, HEIGHT // CELL_SIZE
CELL_COLOR_NOT_VISITED = 'Gray'
CELL_COLOR_VISITED = 'Black'
CELL_COLOR_CURRENT = 'Cyan'
GRID_COLOR = 'Indigo'
